import { Post } from './posts.entity';

const authors = [
  {
    id: 1,
    name: 'Ana Beatriz',
    username: 'anabeatriz_dev',
    avatar: '/images/avatars/bia.png',
  },
  {
    id: 2,
    name: 'Carlos Silva',
    username: 'carlossilva',
    avatar: '/images/avatars/perfil.png',
  },
  {
    id: 3,
    name: 'Julia Souza',
    username: 'juliasouza',
    avatar: '/images/avatars/avatar4.png',
  },
];

export const POSTS_DATA: Post[] = [
  {
    id: 1,
    title: 'Criando componentes reutilizáveis com React',
    description:
      'Aprenda as melhores práticas para criar componentes React que podem ser reutilizados em diferentes partes da sua aplicação.',
    slug: 'criando-componentes-reutilizaveis-com-react',
    coverImage: '/images/cards/img1.png',
    author: authors[0],
    likes: 142,
    comments: 23,
    tags: ['react', 'javascript', 'frontend'],
    createdAt: '2024-11-10T10:00:00Z',
  },
  {
    id: 2,
    title: 'TypeScript avançado: generics e utility types',
    description:
      'Domine os tipos avançados do TypeScript e escreva código mais seguro e expressivo com generics e os utility types nativos.',
    slug: 'typescript-avancado-generics-utility-types',
    coverImage: '/images/cards/img2.png',
    author: authors[1],
    likes: 98,
    comments: 15,
    tags: ['typescript', 'javascript'],
    createdAt: '2024-11-12T14:30:00Z',
  },
  {
    id: 3,
    title: 'NestJS do zero: construindo APIs REST robustas',
    description:
      'Guia completo para criar APIs REST com NestJS, cobrindo módulos, controllers, services, DTOs e validação.',
    slug: 'nestjs-do-zero-apis-rest-robustas',
    coverImage: '/images/cards/img3.png',
    author: authors[2],
    likes: 213,
    comments: 41,
    tags: ['nestjs', 'nodejs', 'backend', 'typescript'],
    createdAt: '2024-11-15T09:00:00Z',
  },
  {
    id: 4,
    title: 'CSS Grid vs Flexbox: quando usar cada um?',
    description:
      'Uma comparação detalhada entre CSS Grid e Flexbox com exemplos práticos para você saber qual layout usar em cada situação.',
    slug: 'css-grid-vs-flexbox-quando-usar',
    coverImage: '/images/cards/img4.png',
    author: authors[0],
    likes: 175,
    comments: 32,
    tags: ['css', 'frontend', 'design'],
    createdAt: '2024-11-18T11:00:00Z',
  },
  {
    id: 5,
    title: 'Introdução ao Docker para desenvolvedores frontend',
    description:
      'Entenda como o Docker pode simplificar seu ambiente de desenvolvimento e facilitar o deploy das suas aplicações.',
    slug: 'introducao-docker-desenvolvedores-frontend',
    coverImage: '/images/cards/img5.png',
    author: authors[1],
    likes: 87,
    comments: 19,
    tags: ['docker', 'devops', 'frontend'],
    createdAt: '2024-11-20T16:00:00Z',
  },
  {
    id: 6,
    title: 'Testes automatizados com Jest e Testing Library',
    description:
      'Aprenda a escrever testes unitários e de integração para suas aplicações React usando Jest e React Testing Library.',
    slug: 'testes-automatizados-jest-testing-library',
    coverImage: '/images/cards/img6.png',
    author: authors[2],
    likes: 134,
    comments: 28,
    tags: ['testes', 'jest', 'react'],
    createdAt: '2024-11-22T08:30:00Z',
  },
  {
    id: 7,
    title: 'Acessibilidade na web: guia prático para devs',
    description:
      'Como tornar suas aplicações web mais acessíveis com ARIA, semântica HTML e boas práticas de UX inclusivo.',
    slug: 'acessibilidade-na-web-guia-pratico',
    coverImage: '/images/cards/img7.png',
    author: authors[0],
    likes: 201,
    comments: 37,
    tags: ['acessibilidade', 'html', 'ux'],
    createdAt: '2024-11-25T13:00:00Z',
  },
  {
    id: 8,
    title: 'Gerenciamento de estado com Zustand',
    description:
      'Conheça o Zustand, uma alternativa simples e poderosa ao Redux para gerenciamento de estado em aplicações React.',
    slug: 'gerenciamento-de-estado-com-zustand',
    coverImage: '/images/cards/img8.png',
    author: authors[1],
    likes: 119,
    comments: 22,
    tags: ['react', 'zustand', 'estado'],
    createdAt: '2024-11-28T10:30:00Z',
  },
  {
    id: 9,
    title: 'Next.js 14: App Router na prática',
    description:
      'Explore as novidades do Next.js 14 com App Router, Server Components, Server Actions e o novo sistema de caching.',
    slug: 'nextjs-14-app-router-na-pratica',
    coverImage: '/images/cards/img9.png',
    author: authors[2],
    likes: 289,
    comments: 54,
    tags: ['nextjs', 'react', 'frontend'],
    createdAt: '2024-12-01T09:00:00Z',
  },
  {
    id: 10,
    title: 'Algoritmos e estruturas de dados em JavaScript',
    description:
      'Uma abordagem prática para aprender os principais algoritmos e estruturas de dados usando JavaScript moderno.',
    slug: 'algoritmos-estruturas-de-dados-javascript',
    coverImage: '/images/cards/img10.png',
    author: authors[0],
    likes: 156,
    comments: 29,
    tags: ['javascript', 'algoritmos', 'cs'],
    createdAt: '2024-12-03T14:00:00Z',
  },
  {
    id: 11,
    title: 'GraphQL com Apollo Client e React',
    description:
      'Substitua suas chamadas REST por GraphQL usando Apollo Client e aproveite ao máximo as queries tipadas.',
    slug: 'graphql-com-apollo-client-e-react',
    coverImage: '/images/cards/img11.png',
    author: authors[1],
    likes: 93,
    comments: 17,
    tags: ['graphql', 'apollo', 'react'],
    createdAt: '2024-12-05T11:30:00Z',
  },
  {
    id: 12,
    title: 'Performance web: otimizando o Core Web Vitals',
    description:
      'Técnicas avançadas para melhorar LCP, FID e CLS e garantir uma experiência rápida para os usuários da sua aplicação.',
    slug: 'performance-web-otimizando-core-web-vitals',
    coverImage: '/images/cards/img12.png',
    author: authors[2],
    likes: 178,
    comments: 33,
    tags: ['performance', 'web', 'frontend'],
    createdAt: '2024-12-08T09:00:00Z',
  },
  {
    id: 13,
    title: 'Monorepos com Turborepo e pnpm workspaces',
    description:
      'Como estruturar projetos grandes usando monorepo com Turborepo, pnpm workspaces e pipelines de build compartilhadas.',
    slug: 'monorepos-turborepo-pnpm-workspaces',
    coverImage: '/images/cards/img13.png',
    author: authors[0],
    likes: 112,
    comments: 21,
    tags: ['monorepo', 'turborepo', 'pnpm'],
    createdAt: '2024-12-10T16:00:00Z',
  },
];
